version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "react"
        versions: ["17.x"]
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    reviewers:
      - "qetqet910"
    assignees:
      - "qetqet910"
    delete-branch: true # ✅ PR 병합 후 브랜치 자동 삭제!
