version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    reviewers:
      - "qetqet910"
    assignees:
      - "qetqet910"
    commit-message:
      prefix: "chore(deps)"
