name: "Auto Merge Dependabot PR"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: "Dependabot 자동 병합"
        if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
